// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: forgekv.proto

package forgekv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Code int32

const (
	Code_CODE_UNSPECIFIED Code = 0
	Code_OK               Code = 1
	Code_NOT_LEADER       Code = 2
	Code_NO_QUORUM        Code = 3
	Code_OVERLOADED       Code = 4
	Code_OUT_OF_ORDER     Code = 5
	Code_INVALID_ARGUMENT Code = 6
	Code_INTERNAL         Code = 7
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0: "CODE_UNSPECIFIED",
		1: "OK",
		2: "NOT_LEADER",
		3: "NO_QUORUM",
		4: "OVERLOADED",
		5: "OUT_OF_ORDER",
		6: "INVALID_ARGUMENT",
		7: "INTERNAL",
	}
	Code_value = map[string]int32{
		"CODE_UNSPECIFIED": 0,
		"OK":               1,
		"NOT_LEADER":       2,
		"NO_QUORUM":        3,
		"OVERLOADED":       4,
		"OUT_OF_ORDER":     5,
		"INVALID_ARGUMENT": 6,
		"INTERNAL":         7,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_forgekv_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_forgekv_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_forgekv_proto_rawDescGZIP(), []int{0}
}

type Proposal_Type int32

const (
	Proposal_TYPE_UNSPECIFIED Proposal_Type = 0
	Proposal_PUT              Proposal_Type = 1
	Proposal_DELETE           Proposal_Type = 2
	Proposal_CAS              Proposal_Type = 3
)

// Enum value maps for Proposal_Type.
var (
	Proposal_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "PUT",
		2: "DELETE",
		3: "CAS",
	}
	Proposal_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"PUT":              1,
		"DELETE":           2,
		"CAS":              3,
	}
)

func (x Proposal_Type) Enum() *Proposal_Type {
	p := new(Proposal_Type)
	*p = x
	return p
}

func (x Proposal_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Proposal_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_forgekv_proto_enumTypes[1].Descriptor()
}

func (Proposal_Type) Type() protoreflect.EnumType {
	return &file_forgekv_proto_enumTypes[1]
}

func (x Proposal_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Proposal_Type.Descriptor instead.
func (Proposal_Type) EnumDescriptor() ([]byte, []int) {
	return file_forgekv_proto_rawDescGZIP(), []int{24, 0}
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Code                   `protobuf:"varint,1,opt,name=code,proto3,enum=forgekv.v1.Code" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	LeaderHint    *LeaderHint            `protobuf:"bytes,3,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_forgekv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_forgekv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_forgekv_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_CODE_UNSPECIFIED
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetLeaderHint() *LeaderHint {
	if x != nil {
		return x.LeaderHint
	}
	return nil
}

type LeaderHint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ClientAddr    string                 `protobuf:"bytes,2,opt,name=client_addr,json=clientAddr,proto3" json:"client_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderHint) Reset() {
	*x = LeaderHint{}
	mi := &file_forgekv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderHint) ProtoMessage() {}

func (x *LeaderHint) ProtoReflect() protoreflect.Message {
	mi := &file_forgekv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderHint.ProtoReflect.Descriptor instead.
func (*LeaderHint) Descriptor() ([]byte, []int) {
	return file_forgekv_proto_rawDescGZIP(), []int{1}
}

func (x *LeaderHint) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *LeaderHint) GetClientAddr() string {
	if x != nil {
		return x.ClientAddr
	}
	return ""
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_forgekv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forgekv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_forgekv_proto_rawDescGZIP(), []int{2}
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PutRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_forgekv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forgekv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_forgekv_proto_rawDescGZIP(), []int{3}
}

func (x *PutResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_forgekv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forgekv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_forgekv_proto_rawDescGZIP(), []int{4}
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_forgekv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forgekv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_forgekv_proto_rawDescGZIP(), []int{5}
}

func (x *GetResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_forgekv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forgekv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_forgekv_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *DeleteRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *DeleteRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_forgekv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forgekv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_forgekv_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type CASRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Expected      []byte                 `protobuf:"bytes,2,opt,name=expected,proto3" json:"expected,omitempty"`
	Desired       []byte                 `protobuf:"bytes,3,opt,name=desired,proto3" json:"desired,omitempty"`
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,5,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CASRequest) Reset() {
	*x = CASRequest{}
	mi := &file_forgekv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CASRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CASRequest) ProtoMessage() {}

func (x *CASRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forgekv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CASRequest.ProtoReflect.Descriptor instead.
func (*CASRequest) Descriptor() ([]byte, []int) {
	return file_forgekv_proto_rawDescGZIP(), []int{8}
}

func (x *CASRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *CASRequest) GetExpected() []byte {
	if x != nil {
		return x.Expected
	}
	return nil
}

func (x *CASRequest) GetDesired() []byte {
	if x != nil {
		return x.Desired
	}
	return nil
}

func (x *CASRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CASRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type CASResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Swapped       bool                   `protobuf:"varint,2,opt,name=swapped,proto3" json:"swapped,omitempty"`
	Current       []byte                 `protobuf:"bytes,3,opt,name=current,proto3" json:"current,omitempty"`
	Found         bool                   `protobuf:"varint,4,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CASResponse) Reset() {
	*x = CASResponse{}
	mi := &file_forgekv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CASResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CASResponse) ProtoMessage() {}

func (x *CASResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forgekv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CASResponse.ProtoReflect.Descriptor instead.
func (*CASResponse) Descriptor() ([]byte, []int) {
	return file_forgekv_proto_rawDescGZIP(), []int{9}
}

func (x *CASResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *CASResponse) GetSwapped() bool {
	if x != nil {
		return x.Swapped
	}
	return false
}

func (x *CASResponse) GetCurrent() []byte {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *CASResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_forgekv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forgekv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_forgekv_proto_rawDescGZIP(), []int{10}
}

type StatusResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Error              *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	NodeId             string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	IsLeader           bool                   `protobuf:"varint,3,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	LeaderId           string                 `protobuf:"bytes,4,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LeaderClientAddr   string                 `protobuf:"bytes,5,opt,name=leader_client_addr,json=leaderClientAddr,proto3" json:"leader_client_addr,omitempty"`
	Term               uint64                 `protobuf:"varint,6,opt,name=term,proto3" json:"term,omitempty"`
	CommitIndex        uint64                 `protobuf:"varint,7,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	AppliedIndex       uint64                 `protobuf:"varint,8,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
	MillisSinceQuorum  uint64                 `protobuf:"varint,9,opt,name=millis_since_quorum,json=millisSinceQuorum,proto3" json:"millis_since_quorum,omitempty"`
	PeerReplicationLag map[string]uint64      `protobuf:"bytes,10,rep,name=peer_replication_lag,json=peerReplicationLag,proto3" json:"peer_replication_lag,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_forgekv_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forgekv_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_forgekv_proto_rawDescGZIP(), []int{11}
}

func (x *StatusResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *StatusResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StatusResponse) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *StatusResponse) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *StatusResponse) GetLeaderClientAddr() string {
	if x != nil {
		return x.LeaderClientAddr
	}
	return ""
}

func (x *StatusResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *StatusResponse) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *StatusResponse) GetAppliedIndex() uint64 {
	if x != nil {
		return x.AppliedIndex
	}
	return 0
}

func (x *StatusResponse) GetMillisSinceQuorum() uint64 {
	if x != nil {
		return x.MillisSinceQuorum
	}
	return 0
}

func (x *StatusResponse) GetPeerReplicationLag() map[string]uint64 {
	if x != nil {
		return x.PeerReplicationLag
	}
	return nil
}

type SetLinkRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcNodeId     string                 `protobuf:"bytes,1,opt,name=src_node_id,json=srcNodeId,proto3" json:"src_node_id,omitempty"`
	DstNodeId     string                 `protobuf:"bytes,2,opt,name=dst_node_id,json=dstNodeId,proto3" json:"dst_node_id,omitempty"`
	DropPct       uint32                 `protobuf:"varint,3,opt,name=drop_pct,json=dropPct,proto3" json:"drop_pct,omitempty"`
	DelayMs       uint32                 `protobuf:"varint,4,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	JitterMs      uint32                 `protobuf:"varint,5,opt,name=jitter_ms,json=jitterMs,proto3" json:"jitter_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLinkRuleRequest) Reset() {
	*x = SetLinkRuleRequest{}
	mi := &file_forgekv_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLinkRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLinkRuleRequest) ProtoMessage() {}

func (x *SetLinkRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forgekv_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLinkRuleRequest.ProtoReflect.Descriptor instead.
func (*SetLinkRuleRequest) Descriptor() ([]byte, []int) {
	return file_forgekv_proto_rawDescGZIP(), []int{12}
}

func (x *SetLinkRuleRequest) GetSrcNodeId() string {
	if x != nil {
		return x.SrcNodeId
	}
	return ""
}

func (x *SetLinkRuleRequest) GetDstNodeId() string {
	if x != nil {
		return x.DstNodeId
	}
	return ""
}

func (x *SetLinkRuleRequest) GetDropPct() uint32 {
	if x != nil {
		return x.DropPct
	}
	return 0
}

func (x *SetLinkRuleRequest) GetDelayMs() uint32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

func (x *SetLinkRuleRequest) GetJitterMs() uint32 {
	if x != nil {
		return x.JitterMs
	}
	return 0
}

type SetLinkRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLinkRuleResponse) Reset() {
	*x = SetLinkRuleResponse{}
	mi := &file_forgekv_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLinkRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLinkRuleResponse) ProtoMessage() {}

func (x *SetLinkRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forgekv_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLinkRuleResponse.ProtoReflect.Descriptor instead.
func (*SetLinkRuleResponse) Descriptor() ([]byte, []int) {
	return file_forgekv_proto_rawDescGZIP(), []int{13}
}

func (x *SetLinkRuleResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ClearLinkRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearLinkRulesRequest) Reset() {
	*x = ClearLinkRulesRequest{}
	mi := &file_forgekv_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearLinkRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearLinkRulesRequest) ProtoMessage() {}

func (x *ClearLinkRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forgekv_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearLinkRulesRequest.ProtoReflect.Descriptor instead.
func (*ClearLinkRulesRequest) Descriptor() ([]byte, []int) {
	return file_forgekv_proto_rawDescGZIP(), []int{14}
}

type ClearLinkRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearLinkRulesResponse) Reset() {
	*x = ClearLinkRulesResponse{}
	mi := &file_forgekv_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearLinkRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearLinkRulesResponse) ProtoMessage() {}

func (x *ClearLinkRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forgekv_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearLinkRulesResponse.ProtoReflect.Descriptor instead.
func (*ClearLinkRulesResponse) Descriptor() ([]byte, []int) {
	return file_forgekv_proto_rawDescGZIP(), []int{15}
}

func (x *ClearLinkRulesResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type SetDiskStallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FsyncDelayMs  uint32                 `protobuf:"varint,1,opt,name=fsync_delay_ms,json=fsyncDelayMs,proto3" json:"fsync_delay_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDiskStallRequest) Reset() {
	*x = SetDiskStallRequest{}
	mi := &file_forgekv_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDiskStallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDiskStallRequest) ProtoMessage() {}

func (x *SetDiskStallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forgekv_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDiskStallRequest.ProtoReflect.Descriptor instead.
func (*SetDiskStallRequest) Descriptor() ([]byte, []int) {
	return file_forgekv_proto_rawDescGZIP(), []int{16}
}

func (x *SetDiskStallRequest) GetFsyncDelayMs() uint32 {
	if x != nil {
		return x.FsyncDelayMs
	}
	return 0
}

type SetDiskStallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDiskStallResponse) Reset() {
	*x = SetDiskStallResponse{}
	mi := &file_forgekv_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDiskStallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDiskStallResponse) ProtoMessage() {}

func (x *SetDiskStallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forgekv_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDiskStallResponse.ProtoReflect.Descriptor instead.
func (*SetDiskStallResponse) Descriptor() ([]byte, []int) {
	return file_forgekv_proto_rawDescGZIP(), []int{17}
}

func (x *SetDiskStallResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type CrashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      uint32                 `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrashRequest) Reset() {
	*x = CrashRequest{}
	mi := &file_forgekv_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrashRequest) ProtoMessage() {}

func (x *CrashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forgekv_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrashRequest.ProtoReflect.Descriptor instead.
func (*CrashRequest) Descriptor() ([]byte, []int) {
	return file_forgekv_proto_rawDescGZIP(), []int{18}
}

func (x *CrashRequest) GetExitCode() uint32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type CrashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrashResponse) Reset() {
	*x = CrashResponse{}
	mi := &file_forgekv_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrashResponse) ProtoMessage() {}

func (x *CrashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forgekv_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrashResponse.ProtoReflect.Descriptor instead.
func (*CrashResponse) Descriptor() ([]byte, []int) {
	return file_forgekv_proto_rawDescGZIP(), []int{19}
}

func (x *CrashResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Internal Raft messages
type RaftMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []byte                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftMessageRequest) Reset() {
	*x = RaftMessageRequest{}
	mi := &file_forgekv_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftMessageRequest) ProtoMessage() {}

func (x *RaftMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forgekv_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftMessageRequest.ProtoReflect.Descriptor instead.
func (*RaftMessageRequest) Descriptor() ([]byte, []int) {
	return file_forgekv_proto_rawDescGZIP(), []int{20}
}

func (x *RaftMessageRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type RaftMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftMessageResponse) Reset() {
	*x = RaftMessageResponse{}
	mi := &file_forgekv_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftMessageResponse) ProtoMessage() {}

func (x *RaftMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forgekv_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftMessageResponse.ProtoReflect.Descriptor instead.
func (*RaftMessageResponse) Descriptor() ([]byte, []int) {
	return file_forgekv_proto_rawDescGZIP(), []int{21}
}

func (x *RaftMessageResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type SnapshotChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Done          bool                   `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotChunk) Reset() {
	*x = SnapshotChunk{}
	mi := &file_forgekv_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotChunk) ProtoMessage() {}

func (x *SnapshotChunk) ProtoReflect() protoreflect.Message {
	mi := &file_forgekv_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotChunk.ProtoReflect.Descriptor instead.
func (*SnapshotChunk) Descriptor() ([]byte, []int) {
	return file_forgekv_proto_rawDescGZIP(), []int{22}
}

func (x *SnapshotChunk) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SnapshotChunk) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *SnapshotChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SnapshotChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type SnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_forgekv_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forgekv_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_forgekv_proto_rawDescGZIP(), []int{23}
}

func (x *SnapshotResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Internal proposal encoding
type Proposal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Proposal_Type          `protobuf:"varint,1,opt,name=type,proto3,enum=forgekv.v1.Proposal_Type" json:"type,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Expected      []byte                 `protobuf:"bytes,4,opt,name=expected,proto3" json:"expected,omitempty"`
	Desired       []byte                 `protobuf:"bytes,5,opt,name=desired,proto3" json:"desired,omitempty"`
	ClientId      string                 `protobuf:"bytes,6,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,7,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proposal) Reset() {
	*x = Proposal{}
	mi := &file_forgekv_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proposal) ProtoMessage() {}

func (x *Proposal) ProtoReflect() protoreflect.Message {
	mi := &file_forgekv_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proposal.ProtoReflect.Descriptor instead.
func (*Proposal) Descriptor() ([]byte, []int) {
	return file_forgekv_proto_rawDescGZIP(), []int{24}
}

func (x *Proposal) GetType() Proposal_Type {
	if x != nil {
		return x.Type
	}
	return Proposal_TYPE_UNSPECIFIED
}

func (x *Proposal) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Proposal) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Proposal) GetExpected() []byte {
	if x != nil {
		return x.Expected
	}
	return nil
}

func (x *Proposal) GetDesired() []byte {
	if x != nil {
		return x.Desired
	}
	return nil
}

func (x *Proposal) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Proposal) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// Session state stored in Pebble
type SessionRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastSeq       uint64                 `protobuf:"varint,1,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	LastReply     []byte                 `protobuf:"bytes,2,opt,name=last_reply,json=lastReply,proto3" json:"last_reply,omitempty"`
	LastSeenIndex uint64                 `protobuf:"varint,3,opt,name=last_seen_index,json=lastSeenIndex,proto3" json:"last_seen_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRecord) Reset() {
	*x = SessionRecord{}
	mi := &file_forgekv_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRecord) ProtoMessage() {}

func (x *SessionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_forgekv_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRecord.ProtoReflect.Descriptor instead.
func (*SessionRecord) Descriptor() ([]byte, []int) {
	return file_forgekv_proto_rawDescGZIP(), []int{25}
}

func (x *SessionRecord) GetLastSeq() uint64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *SessionRecord) GetLastReply() []byte {
	if x != nil {
		return x.LastReply
	}
	return nil
}

func (x *SessionRecord) GetLastSeenIndex() uint64 {
	if x != nil {
		return x.LastSeenIndex
	}
	return 0
}

// Reply cache entry
type CachedReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Code                   `protobuf:"varint,1,opt,name=code,proto3,enum=forgekv.v1.Code" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Swapped       bool                   `protobuf:"varint,3,opt,name=swapped,proto3" json:"swapped,omitempty"`
	Current       []byte                 `protobuf:"bytes,4,opt,name=current,proto3" json:"current,omitempty"`
	Found         bool                   `protobuf:"varint,5,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CachedReply) Reset() {
	*x = CachedReply{}
	mi := &file_forgekv_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CachedReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CachedReply) ProtoMessage() {}

func (x *CachedReply) ProtoReflect() protoreflect.Message {
	mi := &file_forgekv_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CachedReply.ProtoReflect.Descriptor instead.
func (*CachedReply) Descriptor() ([]byte, []int) {
	return file_forgekv_proto_rawDescGZIP(), []int{26}
}

func (x *CachedReply) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_CODE_UNSPECIFIED
}

func (x *CachedReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CachedReply) GetSwapped() bool {
	if x != nil {
		return x.Swapped
	}
	return false
}

func (x *CachedReply) GetCurrent() []byte {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *CachedReply) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

var File_forgekv_proto protoreflect.FileDescriptor

const file_forgekv_proto_rawDesc = "" +
	"\n" +
	"\rforgekv.proto\x12\n" +
	"forgekv.v1\"\x80\x01\n" +
	"\x05Error\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.forgekv.v1.CodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\vleader_hint\x18\x03 \x01(\v2\x16.forgekv.v1.LeaderHintR\n" +
	"leaderHint\"F\n" +
	"\n" +
	"LeaderHint\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vclient_addr\x18\x02 \x01(\tR\n" +
	"clientAddr\"c\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\"6\n" +
	"\vPutResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\x11.forgekv.v1.ErrorR\x05error\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"b\n" +
	"\vGetResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\x11.forgekv.v1.ErrorR\x05error\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\"P\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\"9\n" +
	"\x0eDeleteResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\x11.forgekv.v1.ErrorR\x05error\"\x83\x01\n" +
	"\n" +
	"CASRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x1a\n" +
	"\bexpected\x18\x02 \x01(\fR\bexpected\x12\x18\n" +
	"\adesired\x18\x03 \x01(\fR\adesired\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12\x10\n" +
	"\x03seq\x18\x05 \x01(\x04R\x03seq\"\x80\x01\n" +
	"\vCASResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\x11.forgekv.v1.ErrorR\x05error\x12\x18\n" +
	"\aswapped\x18\x02 \x01(\bR\aswapped\x12\x18\n" +
	"\acurrent\x18\x03 \x01(\fR\acurrent\x12\x14\n" +
	"\x05found\x18\x04 \x01(\bR\x05found\"\x0f\n" +
	"\rStatusRequest\"\xf3\x03\n" +
	"\x0eStatusResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\x11.forgekv.v1.ErrorR\x05error\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tis_leader\x18\x03 \x01(\bR\bisLeader\x12\x1b\n" +
	"\tleader_id\x18\x04 \x01(\tR\bleaderId\x12,\n" +
	"\x12leader_client_addr\x18\x05 \x01(\tR\x10leaderClientAddr\x12\x12\n" +
	"\x04term\x18\x06 \x01(\x04R\x04term\x12!\n" +
	"\fcommit_index\x18\a \x01(\x04R\vcommitIndex\x12#\n" +
	"\rapplied_index\x18\b \x01(\x04R\fappliedIndex\x12.\n" +
	"\x13millis_since_quorum\x18\t \x01(\x04R\x11millisSinceQuorum\x12d\n" +
	"\x14peer_replication_lag\x18\n" +
	" \x03(\v22.forgekv.v1.StatusResponse.PeerReplicationLagEntryR\x12peerReplicationLag\x1aE\n" +
	"\x17PeerReplicationLagEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\xa7\x01\n" +
	"\x12SetLinkRuleRequest\x12\x1e\n" +
	"\vsrc_node_id\x18\x01 \x01(\tR\tsrcNodeId\x12\x1e\n" +
	"\vdst_node_id\x18\x02 \x01(\tR\tdstNodeId\x12\x19\n" +
	"\bdrop_pct\x18\x03 \x01(\rR\adropPct\x12\x19\n" +
	"\bdelay_ms\x18\x04 \x01(\rR\adelayMs\x12\x1b\n" +
	"\tjitter_ms\x18\x05 \x01(\rR\bjitterMs\">\n" +
	"\x13SetLinkRuleResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\x11.forgekv.v1.ErrorR\x05error\"\x17\n" +
	"\x15ClearLinkRulesRequest\"A\n" +
	"\x16ClearLinkRulesResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\x11.forgekv.v1.ErrorR\x05error\";\n" +
	"\x13SetDiskStallRequest\x12$\n" +
	"\x0efsync_delay_ms\x18\x01 \x01(\rR\ffsyncDelayMs\"?\n" +
	"\x14SetDiskStallResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\x11.forgekv.v1.ErrorR\x05error\"+\n" +
	"\fCrashRequest\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\rR\bexitCode\"8\n" +
	"\rCrashResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\x11.forgekv.v1.ErrorR\x05error\".\n" +
	"\x12RaftMessageRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\fR\amessage\">\n" +
	"\x13RaftMessageResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\x11.forgekv.v1.ErrorR\x05error\"a\n" +
	"\rSnapshotChunk\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x12\n" +
	"\x04done\x18\x04 \x01(\bR\x04done\";\n" +
	"\x10SnapshotResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\x11.forgekv.v1.ErrorR\x05error\"\x82\x02\n" +
	"\bProposal\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.forgekv.v1.Proposal.TypeR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x1a\n" +
	"\bexpected\x18\x04 \x01(\fR\bexpected\x12\x18\n" +
	"\adesired\x18\x05 \x01(\fR\adesired\x12\x1b\n" +
	"\tclient_id\x18\x06 \x01(\tR\bclientId\x12\x10\n" +
	"\x03seq\x18\a \x01(\x04R\x03seq\":\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03PUT\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x02\x12\a\n" +
	"\x03CAS\x10\x03\"q\n" +
	"\rSessionRecord\x12\x19\n" +
	"\blast_seq\x18\x01 \x01(\x04R\alastSeq\x12\x1d\n" +
	"\n" +
	"last_reply\x18\x02 \x01(\fR\tlastReply\x12&\n" +
	"\x0flast_seen_index\x18\x03 \x01(\x04R\rlastSeenIndex\"\x97\x01\n" +
	"\vCachedReply\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.forgekv.v1.CodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\aswapped\x18\x03 \x01(\bR\aswapped\x12\x18\n" +
	"\acurrent\x18\x04 \x01(\fR\acurrent\x12\x14\n" +
	"\x05found\x18\x05 \x01(\bR\x05found*\x89\x01\n" +
	"\x04Code\x12\x14\n" +
	"\x10CODE_UNSPECIFIED\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\x0e\n" +
	"\n" +
	"NOT_LEADER\x10\x02\x12\r\n" +
	"\tNO_QUORUM\x10\x03\x12\x0e\n" +
	"\n" +
	"OVERLOADED\x10\x04\x12\x10\n" +
	"\fOUT_OF_ORDER\x10\x05\x12\x14\n" +
	"\x10INVALID_ARGUMENT\x10\x06\x12\f\n" +
	"\bINTERNAL\x10\a2\xae\x02\n" +
	"\x02KV\x126\n" +
	"\x03Put\x12\x16.forgekv.v1.PutRequest\x1a\x17.forgekv.v1.PutResponse\x126\n" +
	"\x03Get\x12\x16.forgekv.v1.GetRequest\x1a\x17.forgekv.v1.GetResponse\x12?\n" +
	"\x06Delete\x12\x19.forgekv.v1.DeleteRequest\x1a\x1a.forgekv.v1.DeleteResponse\x126\n" +
	"\x03CAS\x12\x16.forgekv.v1.CASRequest\x1a\x17.forgekv.v1.CASResponse\x12?\n" +
	"\x06Status\x12\x19.forgekv.v1.StatusRequest\x1a\x1a.forgekv.v1.StatusResponse2\xc1\x02\n" +
	"\x05Admin\x12N\n" +
	"\vSetLinkRule\x12\x1e.forgekv.v1.SetLinkRuleRequest\x1a\x1f.forgekv.v1.SetLinkRuleResponse\x12W\n" +
	"\x0eClearLinkRules\x12!.forgekv.v1.ClearLinkRulesRequest\x1a\".forgekv.v1.ClearLinkRulesResponse\x12Q\n" +
	"\fSetDiskStall\x12\x1f.forgekv.v1.SetDiskStallRequest\x1a .forgekv.v1.SetDiskStallResponse\x12<\n" +
	"\x05Crash\x12\x18.forgekv.v1.CrashRequest\x1a\x19.forgekv.v1.CrashResponse2\xaa\x01\n" +
	"\rRaftTransport\x12N\n" +
	"\vSendMessage\x12\x1e.forgekv.v1.RaftMessageRequest\x1a\x1f.forgekv.v1.RaftMessageResponse\x12I\n" +
	"\fSendSnapshot\x12\x19.forgekv.v1.SnapshotChunk\x1a\x1c.forgekv.v1.SnapshotResponse(\x01B(Z&github.com/forgekv/forgekv/api/forgekvb\x06proto3"

var (
	file_forgekv_proto_rawDescOnce sync.Once
	file_forgekv_proto_rawDescData []byte
)

func file_forgekv_proto_rawDescGZIP() []byte {
	file_forgekv_proto_rawDescOnce.Do(func() {
		file_forgekv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_forgekv_proto_rawDesc), len(file_forgekv_proto_rawDesc)))
	})
	return file_forgekv_proto_rawDescData
}

var file_forgekv_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_forgekv_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_forgekv_proto_goTypes = []any{
	(Code)(0),                      // 0: forgekv.v1.Code
	(Proposal_Type)(0),             // 1: forgekv.v1.Proposal.Type
	(*Error)(nil),                  // 2: forgekv.v1.Error
	(*LeaderHint)(nil),             // 3: forgekv.v1.LeaderHint
	(*PutRequest)(nil),             // 4: forgekv.v1.PutRequest
	(*PutResponse)(nil),            // 5: forgekv.v1.PutResponse
	(*GetRequest)(nil),             // 6: forgekv.v1.GetRequest
	(*GetResponse)(nil),            // 7: forgekv.v1.GetResponse
	(*DeleteRequest)(nil),          // 8: forgekv.v1.DeleteRequest
	(*DeleteResponse)(nil),         // 9: forgekv.v1.DeleteResponse
	(*CASRequest)(nil),             // 10: forgekv.v1.CASRequest
	(*CASResponse)(nil),            // 11: forgekv.v1.CASResponse
	(*StatusRequest)(nil),          // 12: forgekv.v1.StatusRequest
	(*StatusResponse)(nil),         // 13: forgekv.v1.StatusResponse
	(*SetLinkRuleRequest)(nil),     // 14: forgekv.v1.SetLinkRuleRequest
	(*SetLinkRuleResponse)(nil),    // 15: forgekv.v1.SetLinkRuleResponse
	(*ClearLinkRulesRequest)(nil),  // 16: forgekv.v1.ClearLinkRulesRequest
	(*ClearLinkRulesResponse)(nil), // 17: forgekv.v1.ClearLinkRulesResponse
	(*SetDiskStallRequest)(nil),    // 18: forgekv.v1.SetDiskStallRequest
	(*SetDiskStallResponse)(nil),   // 19: forgekv.v1.SetDiskStallResponse
	(*CrashRequest)(nil),           // 20: forgekv.v1.CrashRequest
	(*CrashResponse)(nil),          // 21: forgekv.v1.CrashResponse
	(*RaftMessageRequest)(nil),     // 22: forgekv.v1.RaftMessageRequest
	(*RaftMessageResponse)(nil),    // 23: forgekv.v1.RaftMessageResponse
	(*SnapshotChunk)(nil),          // 24: forgekv.v1.SnapshotChunk
	(*SnapshotResponse)(nil),       // 25: forgekv.v1.SnapshotResponse
	(*Proposal)(nil),               // 26: forgekv.v1.Proposal
	(*SessionRecord)(nil),          // 27: forgekv.v1.SessionRecord
	(*CachedReply)(nil),            // 28: forgekv.v1.CachedReply
	nil,                            // 29: forgekv.v1.StatusResponse.PeerReplicationLagEntry
}
var file_forgekv_proto_depIdxs = []int32{
	0,  // 0: forgekv.v1.Error.code:type_name -> forgekv.v1.Code
	3,  // 1: forgekv.v1.Error.leader_hint:type_name -> forgekv.v1.LeaderHint
	2,  // 2: forgekv.v1.PutResponse.error:type_name -> forgekv.v1.Error
	2,  // 3: forgekv.v1.GetResponse.error:type_name -> forgekv.v1.Error
	2,  // 4: forgekv.v1.DeleteResponse.error:type_name -> forgekv.v1.Error
	2,  // 5: forgekv.v1.CASResponse.error:type_name -> forgekv.v1.Error
	2,  // 6: forgekv.v1.StatusResponse.error:type_name -> forgekv.v1.Error
	29, // 7: forgekv.v1.StatusResponse.peer_replication_lag:type_name -> forgekv.v1.StatusResponse.PeerReplicationLagEntry
	2,  // 8: forgekv.v1.SetLinkRuleResponse.error:type_name -> forgekv.v1.Error
	2,  // 9: forgekv.v1.ClearLinkRulesResponse.error:type_name -> forgekv.v1.Error
	2,  // 10: forgekv.v1.SetDiskStallResponse.error:type_name -> forgekv.v1.Error
	2,  // 11: forgekv.v1.CrashResponse.error:type_name -> forgekv.v1.Error
	2,  // 12: forgekv.v1.RaftMessageResponse.error:type_name -> forgekv.v1.Error
	2,  // 13: forgekv.v1.SnapshotResponse.error:type_name -> forgekv.v1.Error
	1,  // 14: forgekv.v1.Proposal.type:type_name -> forgekv.v1.Proposal.Type
	0,  // 15: forgekv.v1.CachedReply.code:type_name -> forgekv.v1.Code
	4,  // 16: forgekv.v1.KV.Put:input_type -> forgekv.v1.PutRequest
	6,  // 17: forgekv.v1.KV.Get:input_type -> forgekv.v1.GetRequest
	8,  // 18: forgekv.v1.KV.Delete:input_type -> forgekv.v1.DeleteRequest
	10, // 19: forgekv.v1.KV.CAS:input_type -> forgekv.v1.CASRequest
	12, // 20: forgekv.v1.KV.Status:input_type -> forgekv.v1.StatusRequest
	14, // 21: forgekv.v1.Admin.SetLinkRule:input_type -> forgekv.v1.SetLinkRuleRequest
	16, // 22: forgekv.v1.Admin.ClearLinkRules:input_type -> forgekv.v1.ClearLinkRulesRequest
	18, // 23: forgekv.v1.Admin.SetDiskStall:input_type -> forgekv.v1.SetDiskStallRequest
	20, // 24: forgekv.v1.Admin.Crash:input_type -> forgekv.v1.CrashRequest
	22, // 25: forgekv.v1.RaftTransport.SendMessage:input_type -> forgekv.v1.RaftMessageRequest
	24, // 26: forgekv.v1.RaftTransport.SendSnapshot:input_type -> forgekv.v1.SnapshotChunk
	5,  // 27: forgekv.v1.KV.Put:output_type -> forgekv.v1.PutResponse
	7,  // 28: forgekv.v1.KV.Get:output_type -> forgekv.v1.GetResponse
	9,  // 29: forgekv.v1.KV.Delete:output_type -> forgekv.v1.DeleteResponse
	11, // 30: forgekv.v1.KV.CAS:output_type -> forgekv.v1.CASResponse
	13, // 31: forgekv.v1.KV.Status:output_type -> forgekv.v1.StatusResponse
	15, // 32: forgekv.v1.Admin.SetLinkRule:output_type -> forgekv.v1.SetLinkRuleResponse
	17, // 33: forgekv.v1.Admin.ClearLinkRules:output_type -> forgekv.v1.ClearLinkRulesResponse
	19, // 34: forgekv.v1.Admin.SetDiskStall:output_type -> forgekv.v1.SetDiskStallResponse
	21, // 35: forgekv.v1.Admin.Crash:output_type -> forgekv.v1.CrashResponse
	23, // 36: forgekv.v1.RaftTransport.SendMessage:output_type -> forgekv.v1.RaftMessageResponse
	25, // 37: forgekv.v1.RaftTransport.SendSnapshot:output_type -> forgekv.v1.SnapshotResponse
	27, // [27:38] is the sub-list for method output_type
	16, // [16:27] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_forgekv_proto_init() }
func file_forgekv_proto_init() {
	if File_forgekv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_forgekv_proto_rawDesc), len(file_forgekv_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_forgekv_proto_goTypes,
		DependencyIndexes: file_forgekv_proto_depIdxs,
		EnumInfos:         file_forgekv_proto_enumTypes,
		MessageInfos:      file_forgekv_proto_msgTypes,
	}.Build()
	File_forgekv_proto = out.File
	file_forgekv_proto_goTypes = nil
	file_forgekv_proto_depIdxs = nil
}
